//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.21 at 12:15:07 PM CEST 
//


package nl.vpro.smil;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for fitAttributeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="fitAttributeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="fill"/>
 *     &lt;enumeration value="hidden"/>
 *     &lt;enumeration value="meet"/>
 *     &lt;enumeration value="scroll"/>
 *     &lt;enumeration value="slice"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "fitAttributeType")
@XmlEnum
public enum FitAttributeType {

    @XmlEnumValue("fill")
    FILL("fill"),
    @XmlEnumValue("hidden")
    HIDDEN("hidden"),
    @XmlEnumValue("meet")
    MEET("meet"),
    @XmlEnumValue("scroll")
    SCROLL("scroll"),
    @XmlEnumValue("slice")
    SLICE("slice");
    private final String value;

    FitAttributeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FitAttributeType fromValue(String v) {
        for (FitAttributeType c: FitAttributeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
