//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.21 at 12:15:07 PM CEST 
//


package nl.vpro.smil;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for opaqueOrTransparentType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="opaqueOrTransparentType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="opaque"/>
 *     &lt;enumeration value="transparent"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "opaqueOrTransparentType")
@XmlEnum
public enum OpaqueOrTransparentType {

    @XmlEnumValue("opaque")
    OPAQUE("opaque"),
    @XmlEnumValue("transparent")
    TRANSPARENT("transparent");
    private final String value;

    OpaqueOrTransparentType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static OpaqueOrTransparentType fromValue(String v) {
        for (OpaqueOrTransparentType c: OpaqueOrTransparentType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
