//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.21 at 12:15:07 PM CEST 
//


package nl.vpro.smil;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import org.w3._2001.smil20.language.PriorityClassType;


/**
 * <p>Java class for priorityClassPrototype complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="priorityClassPrototype">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="peers" default="stop">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="stop"/>
 *             &lt;enumeration value="pause"/>
 *             &lt;enumeration value="defer"/>
 *             &lt;enumeration value="never"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="higher" default="pause">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="stop"/>
 *             &lt;enumeration value="pause"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="lower" default="defer">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="defer"/>
 *             &lt;enumeration value="never"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="pauseDisplay" default="show">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="disable"/>
 *             &lt;enumeration value="hide"/>
 *             &lt;enumeration value="show"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "priorityClassPrototype")
@XmlSeeAlso({
    PriorityClassType.class
})
public class PriorityClassPrototype {

    @XmlAttribute(name = "peers")
    protected String peers;
    @XmlAttribute(name = "higher")
    protected String higher;
    @XmlAttribute(name = "lower")
    protected String lower;
    @XmlAttribute(name = "pauseDisplay")
    protected String pauseDisplay;

    /**
     * Gets the value of the peers property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPeers() {
        if (peers == null) {
            return "stop";
        } else {
            return peers;
        }
    }

    /**
     * Sets the value of the peers property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPeers(String value) {
        this.peers = value;
    }

    /**
     * Gets the value of the higher property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHigher() {
        if (higher == null) {
            return "pause";
        } else {
            return higher;
        }
    }

    /**
     * Sets the value of the higher property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHigher(String value) {
        this.higher = value;
    }

    /**
     * Gets the value of the lower property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLower() {
        if (lower == null) {
            return "defer";
        } else {
            return lower;
        }
    }

    /**
     * Sets the value of the lower property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLower(String value) {
        this.lower = value;
    }

    /**
     * Gets the value of the pauseDisplay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPauseDisplay() {
        if (pauseDisplay == null) {
            return "show";
        } else {
            return pauseDisplay;
        }
    }

    /**
     * Sets the value of the pauseDisplay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPauseDisplay(String value) {
        this.pauseDisplay = value;
    }

}
