//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.21 at 12:15:07 PM CEST 
//


package nl.vpro.smil;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import org.w3._2001.smil20.language.RegPointType;


/**
 * <p>Java class for regPointPrototype complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="regPointPrototype">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="bottom" type="{http://www.w3.org/2001/XMLSchema}string" default="auto" />
 *       &lt;attribute name="left" type="{http://www.w3.org/2001/XMLSchema}string" default="auto" />
 *       &lt;attribute name="right" type="{http://www.w3.org/2001/XMLSchema}string" default="auto" />
 *       &lt;attribute name="top" type="{http://www.w3.org/2001/XMLSchema}string" default="auto" />
 *       &lt;attribute name="regAlign" type="{http://www.w3.org/2001/SMIL20/}regPointAlignValueType" default="topLeft" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "regPointPrototype")
@XmlSeeAlso({
    RegPointType.class
})
public class RegPointPrototype {

    @XmlAttribute(name = "bottom")
    protected String bottom;
    @XmlAttribute(name = "left")
    protected String left;
    @XmlAttribute(name = "right")
    protected String right;
    @XmlAttribute(name = "top")
    protected String top;
    @XmlAttribute(name = "regAlign")
    protected RegPointAlignValueType regAlign;

    /**
     * Gets the value of the bottom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBottom() {
        if (bottom == null) {
            return "auto";
        } else {
            return bottom;
        }
    }

    /**
     * Sets the value of the bottom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBottom(String value) {
        this.bottom = value;
    }

    /**
     * Gets the value of the left property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLeft() {
        if (left == null) {
            return "auto";
        } else {
            return left;
        }
    }

    /**
     * Sets the value of the left property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLeft(String value) {
        this.left = value;
    }

    /**
     * Gets the value of the right property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRight() {
        if (right == null) {
            return "auto";
        } else {
            return right;
        }
    }

    /**
     * Sets the value of the right property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRight(String value) {
        this.right = value;
    }

    /**
     * Gets the value of the top property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTop() {
        if (top == null) {
            return "auto";
        } else {
            return top;
        }
    }

    /**
     * Sets the value of the top property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTop(String value) {
        this.top = value;
    }

    /**
     * Gets the value of the regAlign property.
     * 
     * @return
     *     possible object is
     *     {@link RegPointAlignValueType }
     *     
     */
    public RegPointAlignValueType getRegAlign() {
        if (regAlign == null) {
            return RegPointAlignValueType.TOP_LEFT;
        } else {
            return regAlign;
        }
    }

    /**
     * Sets the value of the regAlign property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegPointAlignValueType }
     *     
     */
    public void setRegAlign(RegPointAlignValueType value) {
        this.regAlign = value;
    }

}
