//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.21 at 12:15:07 PM CEST 
//


package nl.vpro.smil;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.w3._2001.smil20.language.SwitchType;


/**
 * <p>Java class for switchPrototype complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="switchPrototype">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attGroup ref="{http://www.w3.org/2001/SMIL20/}systemTestAttrs"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "switchPrototype")
@XmlSeeAlso({
    SwitchType.class
})
public class SwitchPrototype {

    @XmlAttribute(name = "systemAudioDesc")
    protected OnOrOffType systemAudioDesc;
    @XmlAttribute(name = "systemBitrate")
    protected String systemBitrate;
    @XmlAttribute(name = "systemCaptions")
    protected OnOrOffType systemCaptions;
    @XmlAttribute(name = "systemComponent")
    protected String systemComponent;
    @XmlAttribute(name = "systemCPU")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String systemCPU;
    @XmlAttribute(name = "systemLanguage")
    protected String systemLanguage;
    @XmlAttribute(name = "systemOperatingSystem")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String systemOperatingSystem;
    @XmlAttribute(name = "systemOverdubOrSubtitle")
    protected OverdubOrSubtitleType systemOverdubOrSubtitle;
    @XmlAttribute(name = "systemRequired")
    protected String systemRequired;
    @XmlAttribute(name = "systemScreenDepth")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger systemScreenDepth;
    @XmlAttribute(name = "systemScreenSize")
    protected String systemScreenSize;

    /**
     * Gets the value of the systemAudioDesc property.
     * 
     * @return
     *     possible object is
     *     {@link OnOrOffType }
     *     
     */
    public OnOrOffType getSystemAudioDesc() {
        return systemAudioDesc;
    }

    /**
     * Sets the value of the systemAudioDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link OnOrOffType }
     *     
     */
    public void setSystemAudioDesc(OnOrOffType value) {
        this.systemAudioDesc = value;
    }

    /**
     * Gets the value of the systemBitrate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSystemBitrate() {
        return systemBitrate;
    }

    /**
     * Sets the value of the systemBitrate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSystemBitrate(String value) {
        this.systemBitrate = value;
    }

    /**
     * Gets the value of the systemCaptions property.
     * 
     * @return
     *     possible object is
     *     {@link OnOrOffType }
     *     
     */
    public OnOrOffType getSystemCaptions() {
        return systemCaptions;
    }

    /**
     * Sets the value of the systemCaptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link OnOrOffType }
     *     
     */
    public void setSystemCaptions(OnOrOffType value) {
        this.systemCaptions = value;
    }

    /**
     * Gets the value of the systemComponent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSystemComponent() {
        return systemComponent;
    }

    /**
     * Sets the value of the systemComponent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSystemComponent(String value) {
        this.systemComponent = value;
    }

    /**
     * Gets the value of the systemCPU property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSystemCPU() {
        return systemCPU;
    }

    /**
     * Sets the value of the systemCPU property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSystemCPU(String value) {
        this.systemCPU = value;
    }

    /**
     * Gets the value of the systemLanguage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSystemLanguage() {
        return systemLanguage;
    }

    /**
     * Sets the value of the systemLanguage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSystemLanguage(String value) {
        this.systemLanguage = value;
    }

    /**
     * Gets the value of the systemOperatingSystem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSystemOperatingSystem() {
        return systemOperatingSystem;
    }

    /**
     * Sets the value of the systemOperatingSystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSystemOperatingSystem(String value) {
        this.systemOperatingSystem = value;
    }

    /**
     * Gets the value of the systemOverdubOrSubtitle property.
     * 
     * @return
     *     possible object is
     *     {@link OverdubOrSubtitleType }
     *     
     */
    public OverdubOrSubtitleType getSystemOverdubOrSubtitle() {
        return systemOverdubOrSubtitle;
    }

    /**
     * Sets the value of the systemOverdubOrSubtitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link OverdubOrSubtitleType }
     *     
     */
    public void setSystemOverdubOrSubtitle(OverdubOrSubtitleType value) {
        this.systemOverdubOrSubtitle = value;
    }

    /**
     * Gets the value of the systemRequired property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSystemRequired() {
        return systemRequired;
    }

    /**
     * Sets the value of the systemRequired property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSystemRequired(String value) {
        this.systemRequired = value;
    }

    /**
     * Gets the value of the systemScreenDepth property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSystemScreenDepth() {
        return systemScreenDepth;
    }

    /**
     * Sets the value of the systemScreenDepth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSystemScreenDepth(BigInteger value) {
        this.systemScreenDepth = value;
    }

    /**
     * Gets the value of the systemScreenSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSystemScreenSize() {
        return systemScreenSize;
    }

    /**
     * Sets the value of the systemScreenSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSystemScreenSize(String value) {
        this.systemScreenSize = value;
    }

}
