//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.21 at 12:15:07 PM CEST 
//


package nl.vpro.smil;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for timeActionArgType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="timeActionArgType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="intrinsic"/>
 *     &lt;enumeration value="display"/>
 *     &lt;enumeration value="visibility"/>
 *     &lt;enumeration value="style"/>
 *     &lt;enumeration value="none"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "timeActionArgType")
@XmlEnum
public enum TimeActionArgType {

    @XmlEnumValue("intrinsic")
    INTRINSIC("intrinsic"),
    @XmlEnumValue("display")
    DISPLAY("display"),
    @XmlEnumValue("visibility")
    VISIBILITY("visibility"),
    @XmlEnumValue("style")
    STYLE("style"),
    @XmlEnumValue("none")
    NONE("none");
    private final String value;

    TimeActionArgType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TimeActionArgType fromValue(String v) {
        for (TimeActionArgType c: TimeActionArgType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
