//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.21 at 12:15:07 PM CEST 
//


package nl.vpro.smil;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for transitionPrototype complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="transitionPrototype">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="subtype" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="mode" default="in">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="in"/>
 *             &lt;enumeration value="out"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="dur" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="startProgress" type="{http://www.w3.org/2001/SMIL20/}zeroToOneDecimalType" default="0.0" />
 *       &lt;attribute name="endProgress" type="{http://www.w3.org/2001/SMIL20/}zeroToOneDecimalType" default="1.0" />
 *       &lt;attribute name="direction" default="forward">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="forward"/>
 *             &lt;enumeration value="reverse"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="fadeColor" type="{http://www.w3.org/2001/XMLSchema}string" default="black" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "transitionPrototype")
@XmlSeeAlso({
    nl.vpro.smil.TransitionType.class,
    org.w3._2001.smil20.language.TransitionType.class
})
public class TransitionPrototype {

    @XmlAttribute(name = "type", required = true)
    protected String type;
    @XmlAttribute(name = "subtype")
    protected String subtype;
    @XmlAttribute(name = "mode")
    protected String mode;
    @XmlAttribute(name = "dur")
    protected String dur;
    @XmlAttribute(name = "startProgress")
    protected BigDecimal startProgress;
    @XmlAttribute(name = "endProgress")
    protected BigDecimal endProgress;
    @XmlAttribute(name = "direction")
    protected String direction;
    @XmlAttribute(name = "fadeColor")
    protected String fadeColor;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the subtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubtype() {
        return subtype;
    }

    /**
     * Sets the value of the subtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubtype(String value) {
        this.subtype = value;
    }

    /**
     * Gets the value of the mode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMode() {
        if (mode == null) {
            return "in";
        } else {
            return mode;
        }
    }

    /**
     * Sets the value of the mode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMode(String value) {
        this.mode = value;
    }

    /**
     * Gets the value of the dur property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDur() {
        return dur;
    }

    /**
     * Sets the value of the dur property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDur(String value) {
        this.dur = value;
    }

    /**
     * Gets the value of the startProgress property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getStartProgress() {
        if (startProgress == null) {
            return new BigDecimal("0.0");
        } else {
            return startProgress;
        }
    }

    /**
     * Sets the value of the startProgress property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setStartProgress(BigDecimal value) {
        this.startProgress = value;
    }

    /**
     * Gets the value of the endProgress property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getEndProgress() {
        if (endProgress == null) {
            return new BigDecimal("1.0");
        } else {
            return endProgress;
        }
    }

    /**
     * Sets the value of the endProgress property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEndProgress(BigDecimal value) {
        this.endProgress = value;
    }

    /**
     * Gets the value of the direction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDirection() {
        if (direction == null) {
            return "forward";
        } else {
            return direction;
        }
    }

    /**
     * Sets the value of the direction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDirection(String value) {
        this.direction = value;
    }

    /**
     * Gets the value of the fadeColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFadeColor() {
        if (fadeColor == null) {
            return "black";
        } else {
            return fadeColor;
        }
    }

    /**
     * Sets the value of the fadeColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFadeColor(String value) {
        this.fadeColor = value;
    }

}
