//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.21 at 12:15:07 PM CEST 
//


package org.w3._2001.smil20.hierarchicallayout;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import org.w3._2001.smil20.language.LayoutType;
import org.w3._2001.smil20.language.RegPointType;
import org.w3._2001.smil20.language.RegionType;
import org.w3._2001.smil20.language.RootLayoutType;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.w3._2001.smil20.hierarchicallayout package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RegPoint_QNAME = new QName("http://www.w3.org/2001/SMIL20/HierarchicalLayout", "regPoint");
    private final static QName _Region_QNAME = new QName("http://www.w3.org/2001/SMIL20/HierarchicalLayout", "region");
    private final static QName _Layout_QNAME = new QName("http://www.w3.org/2001/SMIL20/HierarchicalLayout", "layout");
    private final static QName _RootLayout_QNAME = new QName("http://www.w3.org/2001/SMIL20/HierarchicalLayout", "root-layout");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.w3._2001.smil20.hierarchicallayout
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RegPointType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/SMIL20/HierarchicalLayout", name = "regPoint", substitutionHeadNamespace = "http://www.w3.org/2001/SMIL20/Language", substitutionHeadName = "regPoint")
    public JAXBElement<RegPointType> createRegPoint(RegPointType value) {
        return new JAXBElement<RegPointType>(_RegPoint_QNAME, RegPointType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RegionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/SMIL20/HierarchicalLayout", name = "region", substitutionHeadNamespace = "http://www.w3.org/2001/SMIL20/Language", substitutionHeadName = "region")
    public JAXBElement<RegionType> createRegion(RegionType value) {
        return new JAXBElement<RegionType>(_Region_QNAME, RegionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LayoutType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/SMIL20/HierarchicalLayout", name = "layout", substitutionHeadNamespace = "http://www.w3.org/2001/SMIL20/Language", substitutionHeadName = "layout")
    public JAXBElement<LayoutType> createLayout(LayoutType value) {
        return new JAXBElement<LayoutType>(_Layout_QNAME, LayoutType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RootLayoutType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/SMIL20/HierarchicalLayout", name = "root-layout", substitutionHeadNamespace = "http://www.w3.org/2001/SMIL20/Language", substitutionHeadName = "root-layout")
    public JAXBElement<RootLayoutType> createRootLayout(RootLayoutType value) {
        return new JAXBElement<RootLayoutType>(_RootLayout_QNAME, RootLayoutType.class, null, value);
    }

}
