//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.21 at 12:15:07 PM CEST 
//


package org.w3._2001.smil20.language;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.w3._2001.smil20.language package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Layout_QNAME = new QName("http://www.w3.org/2001/SMIL20/Language", "layout");
    private final static QName _Param_QNAME = new QName("http://www.w3.org/2001/SMIL20/Language", "param");
    private final static QName _Head_QNAME = new QName("http://www.w3.org/2001/SMIL20/Language", "head");
    private final static QName _Switch_QNAME = new QName("http://www.w3.org/2001/SMIL20/Language", "switch");
    private final static QName _Smil_QNAME = new QName("http://www.w3.org/2001/SMIL20/Language", "smil");
    private final static QName _Video_QNAME = new QName("http://www.w3.org/2001/SMIL20/Language", "video");
    private final static QName _Prefetch_QNAME = new QName("http://www.w3.org/2001/SMIL20/Language", "prefetch");
    private final static QName _RootLayout_QNAME = new QName("http://www.w3.org/2001/SMIL20/Language", "root-layout");
    private final static QName _Img_QNAME = new QName("http://www.w3.org/2001/SMIL20/Language", "img");
    private final static QName _Region_QNAME = new QName("http://www.w3.org/2001/SMIL20/Language", "region");
    private final static QName _CustomAttributes_QNAME = new QName("http://www.w3.org/2001/SMIL20/Language", "customAttributes");
    private final static QName _AnimateColor_QNAME = new QName("http://www.w3.org/2001/SMIL20/Language", "animateColor");
    private final static QName _PriorityClass_QNAME = new QName("http://www.w3.org/2001/SMIL20/Language", "priorityClass");
    private final static QName _Brush_QNAME = new QName("http://www.w3.org/2001/SMIL20/Language", "brush");
    private final static QName _Area_QNAME = new QName("http://www.w3.org/2001/SMIL20/Language", "area");
    private final static QName _Par_QNAME = new QName("http://www.w3.org/2001/SMIL20/Language", "par");
    private final static QName _Ref_QNAME = new QName("http://www.w3.org/2001/SMIL20/Language", "ref");
    private final static QName _Body_QNAME = new QName("http://www.w3.org/2001/SMIL20/Language", "body");
    private final static QName _Anchor_QNAME = new QName("http://www.w3.org/2001/SMIL20/Language", "anchor");
    private final static QName _Excl_QNAME = new QName("http://www.w3.org/2001/SMIL20/Language", "excl");
    private final static QName _Transition_QNAME = new QName("http://www.w3.org/2001/SMIL20/Language", "transition");
    private final static QName _AnimateMotion_QNAME = new QName("http://www.w3.org/2001/SMIL20/Language", "animateMotion");
    private final static QName _A_QNAME = new QName("http://www.w3.org/2001/SMIL20/Language", "a");
    private final static QName _Set_QNAME = new QName("http://www.w3.org/2001/SMIL20/Language", "set");
    private final static QName _Seq_QNAME = new QName("http://www.w3.org/2001/SMIL20/Language", "seq");
    private final static QName _Audio_QNAME = new QName("http://www.w3.org/2001/SMIL20/Language", "audio");
    private final static QName _TopLayout_QNAME = new QName("http://www.w3.org/2001/SMIL20/Language", "topLayout");
    private final static QName _Meta_QNAME = new QName("http://www.w3.org/2001/SMIL20/Language", "meta");
    private final static QName _Animation_QNAME = new QName("http://www.w3.org/2001/SMIL20/Language", "animation");
    private final static QName _RegPoint_QNAME = new QName("http://www.w3.org/2001/SMIL20/Language", "regPoint");
    private final static QName _CustomTest_QNAME = new QName("http://www.w3.org/2001/SMIL20/Language", "customTest");
    private final static QName _Text_QNAME = new QName("http://www.w3.org/2001/SMIL20/Language", "text");
    private final static QName _Textstream_QNAME = new QName("http://www.w3.org/2001/SMIL20/Language", "textstream");
    private final static QName _Animate_QNAME = new QName("http://www.w3.org/2001/SMIL20/Language", "animate");
    private final static QName _Metadata_QNAME = new QName("http://www.w3.org/2001/SMIL20/Language", "metadata");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.w3._2001.smil20.language
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TopLayoutType }
     * 
     */
    public TopLayoutType createTopLayoutType() {
        return new TopLayoutType();
    }

    /**
     * Create an instance of {@link RootLayoutType }
     * 
     */
    public RootLayoutType createRootLayoutType() {
        return new RootLayoutType();
    }

    /**
     * Create an instance of {@link MediaType }
     * 
     */
    public MediaType createMediaType() {
        return new MediaType();
    }

    /**
     * Create an instance of {@link MetadataType }
     * 
     */
    public MetadataType createMetadataType() {
        return new MetadataType();
    }

    /**
     * Create an instance of {@link PrefetchType }
     * 
     */
    public PrefetchType createPrefetchType() {
        return new PrefetchType();
    }

    /**
     * Create an instance of {@link SmilType }
     * 
     */
    public SmilType createSmilType() {
        return new SmilType();
    }

    /**
     * Create an instance of {@link BodyType }
     * 
     */
    public BodyType createBodyType() {
        return new BodyType();
    }

    /**
     * Create an instance of {@link AnimateType }
     * 
     */
    public AnimateType createAnimateType() {
        return new AnimateType();
    }

    /**
     * Create an instance of {@link SwitchType }
     * 
     */
    public SwitchType createSwitchType() {
        return new SwitchType();
    }

    /**
     * Create an instance of {@link HeadType }
     * 
     */
    public HeadType createHeadType() {
        return new HeadType();
    }

    /**
     * Create an instance of {@link ParamType }
     * 
     */
    public ParamType createParamType() {
        return new ParamType();
    }

    /**
     * Create an instance of {@link CustomTestType }
     * 
     */
    public CustomTestType createCustomTestType() {
        return new CustomTestType();
    }

    /**
     * Create an instance of {@link SeqType }
     * 
     */
    public SeqType createSeqType() {
        return new SeqType();
    }

    /**
     * Create an instance of {@link BrushType }
     * 
     */
    public BrushType createBrushType() {
        return new BrushType();
    }

    /**
     * Create an instance of {@link AreaType }
     * 
     */
    public AreaType createAreaType() {
        return new AreaType();
    }

    /**
     * Create an instance of {@link ParType }
     * 
     */
    public ParType createParType() {
        return new ParType();
    }

    /**
     * Create an instance of {@link AType }
     * 
     */
    public AType createAType() {
        return new AType();
    }

    /**
     * Create an instance of {@link SetType }
     * 
     */
    public SetType createSetType() {
        return new SetType();
    }

    /**
     * Create an instance of {@link RegPointType }
     * 
     */
    public RegPointType createRegPointType() {
        return new RegPointType();
    }

    /**
     * Create an instance of {@link AnimateMotionType }
     * 
     */
    public AnimateMotionType createAnimateMotionType() {
        return new AnimateMotionType();
    }

    /**
     * Create an instance of {@link PriorityClassType }
     * 
     */
    public PriorityClassType createPriorityClassType() {
        return new PriorityClassType();
    }

    /**
     * Create an instance of {@link LayoutType }
     * 
     */
    public LayoutType createLayoutType() {
        return new LayoutType();
    }

    /**
     * Create an instance of {@link ExclType }
     * 
     */
    public ExclType createExclType() {
        return new ExclType();
    }

    /**
     * Create an instance of {@link MetaType }
     * 
     */
    public MetaType createMetaType() {
        return new MetaType();
    }

    /**
     * Create an instance of {@link AnchorType }
     * 
     */
    public AnchorType createAnchorType() {
        return new AnchorType();
    }

    /**
     * Create an instance of {@link AnimateColorType }
     * 
     */
    public AnimateColorType createAnimateColorType() {
        return new AnimateColorType();
    }

    /**
     * Create an instance of {@link RegionType }
     * 
     */
    public RegionType createRegionType() {
        return new RegionType();
    }

    /**
     * Create an instance of {@link CustomAttributesType }
     * 
     */
    public CustomAttributesType createCustomAttributesType() {
        return new CustomAttributesType();
    }

    /**
     * Create an instance of {@link TransitionType }
     * 
     */
    public TransitionType createTransitionType() {
        return new TransitionType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LayoutType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/SMIL20/Language", name = "layout")
    public JAXBElement<LayoutType> createLayout(LayoutType value) {
        return new JAXBElement<LayoutType>(_Layout_QNAME, LayoutType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ParamType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/SMIL20/Language", name = "param")
    public JAXBElement<ParamType> createParam(ParamType value) {
        return new JAXBElement<ParamType>(_Param_QNAME, ParamType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HeadType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/SMIL20/Language", name = "head")
    public JAXBElement<HeadType> createHead(HeadType value) {
        return new JAXBElement<HeadType>(_Head_QNAME, HeadType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SwitchType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/SMIL20/Language", name = "switch")
    public JAXBElement<SwitchType> createSwitch(SwitchType value) {
        return new JAXBElement<SwitchType>(_Switch_QNAME, SwitchType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SmilType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/SMIL20/Language", name = "smil")
    public JAXBElement<SmilType> createSmil(SmilType value) {
        return new JAXBElement<SmilType>(_Smil_QNAME, SmilType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MediaType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/SMIL20/Language", name = "video")
    public JAXBElement<MediaType> createVideo(MediaType value) {
        return new JAXBElement<MediaType>(_Video_QNAME, MediaType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PrefetchType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/SMIL20/Language", name = "prefetch")
    public JAXBElement<PrefetchType> createPrefetch(PrefetchType value) {
        return new JAXBElement<PrefetchType>(_Prefetch_QNAME, PrefetchType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RootLayoutType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/SMIL20/Language", name = "root-layout")
    public JAXBElement<RootLayoutType> createRootLayout(RootLayoutType value) {
        return new JAXBElement<RootLayoutType>(_RootLayout_QNAME, RootLayoutType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MediaType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/SMIL20/Language", name = "img")
    public JAXBElement<MediaType> createImg(MediaType value) {
        return new JAXBElement<MediaType>(_Img_QNAME, MediaType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RegionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/SMIL20/Language", name = "region")
    public JAXBElement<RegionType> createRegion(RegionType value) {
        return new JAXBElement<RegionType>(_Region_QNAME, RegionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CustomAttributesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/SMIL20/Language", name = "customAttributes")
    public JAXBElement<CustomAttributesType> createCustomAttributes(CustomAttributesType value) {
        return new JAXBElement<CustomAttributesType>(_CustomAttributes_QNAME, CustomAttributesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnimateColorType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/SMIL20/Language", name = "animateColor")
    public JAXBElement<AnimateColorType> createAnimateColor(AnimateColorType value) {
        return new JAXBElement<AnimateColorType>(_AnimateColor_QNAME, AnimateColorType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PriorityClassType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/SMIL20/Language", name = "priorityClass")
    public JAXBElement<PriorityClassType> createPriorityClass(PriorityClassType value) {
        return new JAXBElement<PriorityClassType>(_PriorityClass_QNAME, PriorityClassType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BrushType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/SMIL20/Language", name = "brush")
    public JAXBElement<BrushType> createBrush(BrushType value) {
        return new JAXBElement<BrushType>(_Brush_QNAME, BrushType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AreaType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/SMIL20/Language", name = "area")
    public JAXBElement<AreaType> createArea(AreaType value) {
        return new JAXBElement<AreaType>(_Area_QNAME, AreaType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ParType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/SMIL20/Language", name = "par")
    public JAXBElement<ParType> createPar(ParType value) {
        return new JAXBElement<ParType>(_Par_QNAME, ParType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MediaType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/SMIL20/Language", name = "ref")
    public JAXBElement<MediaType> createRef(MediaType value) {
        return new JAXBElement<MediaType>(_Ref_QNAME, MediaType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BodyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/SMIL20/Language", name = "body")
    public JAXBElement<BodyType> createBody(BodyType value) {
        return new JAXBElement<BodyType>(_Body_QNAME, BodyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnchorType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/SMIL20/Language", name = "anchor")
    public JAXBElement<AnchorType> createAnchor(AnchorType value) {
        return new JAXBElement<AnchorType>(_Anchor_QNAME, AnchorType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExclType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/SMIL20/Language", name = "excl")
    public JAXBElement<ExclType> createExcl(ExclType value) {
        return new JAXBElement<ExclType>(_Excl_QNAME, ExclType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TransitionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/SMIL20/Language", name = "transition")
    public JAXBElement<TransitionType> createTransition(TransitionType value) {
        return new JAXBElement<TransitionType>(_Transition_QNAME, TransitionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnimateMotionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/SMIL20/Language", name = "animateMotion")
    public JAXBElement<AnimateMotionType> createAnimateMotion(AnimateMotionType value) {
        return new JAXBElement<AnimateMotionType>(_AnimateMotion_QNAME, AnimateMotionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/SMIL20/Language", name = "a")
    public JAXBElement<AType> createA(AType value) {
        return new JAXBElement<AType>(_A_QNAME, AType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SetType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/SMIL20/Language", name = "set")
    public JAXBElement<SetType> createSet(SetType value) {
        return new JAXBElement<SetType>(_Set_QNAME, SetType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SeqType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/SMIL20/Language", name = "seq")
    public JAXBElement<SeqType> createSeq(SeqType value) {
        return new JAXBElement<SeqType>(_Seq_QNAME, SeqType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MediaType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/SMIL20/Language", name = "audio")
    public JAXBElement<MediaType> createAudio(MediaType value) {
        return new JAXBElement<MediaType>(_Audio_QNAME, MediaType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TopLayoutType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/SMIL20/Language", name = "topLayout")
    public JAXBElement<TopLayoutType> createTopLayout(TopLayoutType value) {
        return new JAXBElement<TopLayoutType>(_TopLayout_QNAME, TopLayoutType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MetaType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/SMIL20/Language", name = "meta")
    public JAXBElement<MetaType> createMeta(MetaType value) {
        return new JAXBElement<MetaType>(_Meta_QNAME, MetaType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MediaType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/SMIL20/Language", name = "animation")
    public JAXBElement<MediaType> createAnimation(MediaType value) {
        return new JAXBElement<MediaType>(_Animation_QNAME, MediaType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RegPointType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/SMIL20/Language", name = "regPoint")
    public JAXBElement<RegPointType> createRegPoint(RegPointType value) {
        return new JAXBElement<RegPointType>(_RegPoint_QNAME, RegPointType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CustomTestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/SMIL20/Language", name = "customTest")
    public JAXBElement<CustomTestType> createCustomTest(CustomTestType value) {
        return new JAXBElement<CustomTestType>(_CustomTest_QNAME, CustomTestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MediaType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/SMIL20/Language", name = "text")
    public JAXBElement<MediaType> createText(MediaType value) {
        return new JAXBElement<MediaType>(_Text_QNAME, MediaType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MediaType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/SMIL20/Language", name = "textstream")
    public JAXBElement<MediaType> createTextstream(MediaType value) {
        return new JAXBElement<MediaType>(_Textstream_QNAME, MediaType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnimateType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/SMIL20/Language", name = "animate")
    public JAXBElement<AnimateType> createAnimate(AnimateType value) {
        return new JAXBElement<AnimateType>(_Animate_QNAME, AnimateType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MetadataType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/SMIL20/Language", name = "metadata")
    public JAXBElement<MetadataType> createMetadata(MetadataType value) {
        return new JAXBElement<MetadataType>(_Metadata_QNAME, MetadataType.class, null, value);
    }

}
