//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.21 at 12:15:07 PM CEST 
//


package org.w3._2001.smil20.hostlanguage;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import org.w3._2001.smil20.language.AType;
import org.w3._2001.smil20.language.AnchorType;
import org.w3._2001.smil20.language.AreaType;
import org.w3._2001.smil20.language.BodyType;
import org.w3._2001.smil20.language.HeadType;
import org.w3._2001.smil20.language.LayoutType;
import org.w3._2001.smil20.language.MediaType;
import org.w3._2001.smil20.language.ParType;
import org.w3._2001.smil20.language.RegionType;
import org.w3._2001.smil20.language.RootLayoutType;
import org.w3._2001.smil20.language.SeqType;
import org.w3._2001.smil20.language.SmilType;
import org.w3._2001.smil20.language.SwitchType;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.w3._2001.smil20.hostlanguage package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Area_QNAME = new QName("http://www.w3.org/2001/SMIL20/HostLanguage", "area");
    private final static QName _Par_QNAME = new QName("http://www.w3.org/2001/SMIL20/HostLanguage", "par");
    private final static QName _Region_QNAME = new QName("http://www.w3.org/2001/SMIL20/HostLanguage", "region");
    private final static QName _Body_QNAME = new QName("http://www.w3.org/2001/SMIL20/HostLanguage", "body");
    private final static QName _Ref_QNAME = new QName("http://www.w3.org/2001/SMIL20/HostLanguage", "ref");
    private final static QName _Layout_QNAME = new QName("http://www.w3.org/2001/SMIL20/HostLanguage", "layout");
    private final static QName _RootLayout_QNAME = new QName("http://www.w3.org/2001/SMIL20/HostLanguage", "root-layout");
    private final static QName _Img_QNAME = new QName("http://www.w3.org/2001/SMIL20/HostLanguage", "img");
    private final static QName _Switch_QNAME = new QName("http://www.w3.org/2001/SMIL20/HostLanguage", "switch");
    private final static QName _Video_QNAME = new QName("http://www.w3.org/2001/SMIL20/HostLanguage", "video");
    private final static QName _Smil_QNAME = new QName("http://www.w3.org/2001/SMIL20/HostLanguage", "smil");
    private final static QName _Head_QNAME = new QName("http://www.w3.org/2001/SMIL20/HostLanguage", "head");
    private final static QName _Animation_QNAME = new QName("http://www.w3.org/2001/SMIL20/HostLanguage", "animation");
    private final static QName _Textstream_QNAME = new QName("http://www.w3.org/2001/SMIL20/HostLanguage", "textstream");
    private final static QName _Text_QNAME = new QName("http://www.w3.org/2001/SMIL20/HostLanguage", "text");
    private final static QName _A_QNAME = new QName("http://www.w3.org/2001/SMIL20/HostLanguage", "a");
    private final static QName _Anchor_QNAME = new QName("http://www.w3.org/2001/SMIL20/HostLanguage", "anchor");
    private final static QName _Seq_QNAME = new QName("http://www.w3.org/2001/SMIL20/HostLanguage", "seq");
    private final static QName _Audio_QNAME = new QName("http://www.w3.org/2001/SMIL20/HostLanguage", "audio");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.w3._2001.smil20.hostlanguage
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AreaType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/SMIL20/HostLanguage", name = "area", substitutionHeadNamespace = "http://www.w3.org/2001/SMIL20/Language", substitutionHeadName = "area")
    public JAXBElement<AreaType> createArea(AreaType value) {
        return new JAXBElement<AreaType>(_Area_QNAME, AreaType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ParType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/SMIL20/HostLanguage", name = "par", substitutionHeadNamespace = "http://www.w3.org/2001/SMIL20/Language", substitutionHeadName = "par")
    public JAXBElement<ParType> createPar(ParType value) {
        return new JAXBElement<ParType>(_Par_QNAME, ParType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RegionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/SMIL20/HostLanguage", name = "region", substitutionHeadNamespace = "http://www.w3.org/2001/SMIL20/Language", substitutionHeadName = "region")
    public JAXBElement<RegionType> createRegion(RegionType value) {
        return new JAXBElement<RegionType>(_Region_QNAME, RegionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BodyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/SMIL20/HostLanguage", name = "body", substitutionHeadNamespace = "http://www.w3.org/2001/SMIL20/Language", substitutionHeadName = "body")
    public JAXBElement<BodyType> createBody(BodyType value) {
        return new JAXBElement<BodyType>(_Body_QNAME, BodyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MediaType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/SMIL20/HostLanguage", name = "ref", substitutionHeadNamespace = "http://www.w3.org/2001/SMIL20/Language", substitutionHeadName = "ref")
    public JAXBElement<MediaType> createRef(MediaType value) {
        return new JAXBElement<MediaType>(_Ref_QNAME, MediaType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LayoutType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/SMIL20/HostLanguage", name = "layout", substitutionHeadNamespace = "http://www.w3.org/2001/SMIL20/Language", substitutionHeadName = "layout")
    public JAXBElement<LayoutType> createLayout(LayoutType value) {
        return new JAXBElement<LayoutType>(_Layout_QNAME, LayoutType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RootLayoutType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/SMIL20/HostLanguage", name = "root-layout", substitutionHeadNamespace = "http://www.w3.org/2001/SMIL20/Language", substitutionHeadName = "root-layout")
    public JAXBElement<RootLayoutType> createRootLayout(RootLayoutType value) {
        return new JAXBElement<RootLayoutType>(_RootLayout_QNAME, RootLayoutType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MediaType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/SMIL20/HostLanguage", name = "img", substitutionHeadNamespace = "http://www.w3.org/2001/SMIL20/Language", substitutionHeadName = "img")
    public JAXBElement<MediaType> createImg(MediaType value) {
        return new JAXBElement<MediaType>(_Img_QNAME, MediaType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SwitchType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/SMIL20/HostLanguage", name = "switch", substitutionHeadNamespace = "http://www.w3.org/2001/SMIL20/Language", substitutionHeadName = "switch")
    public JAXBElement<SwitchType> createSwitch(SwitchType value) {
        return new JAXBElement<SwitchType>(_Switch_QNAME, SwitchType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MediaType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/SMIL20/HostLanguage", name = "video", substitutionHeadNamespace = "http://www.w3.org/2001/SMIL20/Language", substitutionHeadName = "video")
    public JAXBElement<MediaType> createVideo(MediaType value) {
        return new JAXBElement<MediaType>(_Video_QNAME, MediaType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SmilType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/SMIL20/HostLanguage", name = "smil", substitutionHeadNamespace = "http://www.w3.org/2001/SMIL20/Language", substitutionHeadName = "smil")
    public JAXBElement<SmilType> createSmil(SmilType value) {
        return new JAXBElement<SmilType>(_Smil_QNAME, SmilType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HeadType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/SMIL20/HostLanguage", name = "head", substitutionHeadNamespace = "http://www.w3.org/2001/SMIL20/Language", substitutionHeadName = "head")
    public JAXBElement<HeadType> createHead(HeadType value) {
        return new JAXBElement<HeadType>(_Head_QNAME, HeadType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MediaType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/SMIL20/HostLanguage", name = "animation", substitutionHeadNamespace = "http://www.w3.org/2001/SMIL20/Language", substitutionHeadName = "animation")
    public JAXBElement<MediaType> createAnimation(MediaType value) {
        return new JAXBElement<MediaType>(_Animation_QNAME, MediaType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MediaType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/SMIL20/HostLanguage", name = "textstream", substitutionHeadNamespace = "http://www.w3.org/2001/SMIL20/Language", substitutionHeadName = "textstream")
    public JAXBElement<MediaType> createTextstream(MediaType value) {
        return new JAXBElement<MediaType>(_Textstream_QNAME, MediaType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MediaType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/SMIL20/HostLanguage", name = "text", substitutionHeadNamespace = "http://www.w3.org/2001/SMIL20/Language", substitutionHeadName = "text")
    public JAXBElement<MediaType> createText(MediaType value) {
        return new JAXBElement<MediaType>(_Text_QNAME, MediaType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/SMIL20/HostLanguage", name = "a", substitutionHeadNamespace = "http://www.w3.org/2001/SMIL20/Language", substitutionHeadName = "a")
    public JAXBElement<AType> createA(AType value) {
        return new JAXBElement<AType>(_A_QNAME, AType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnchorType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/SMIL20/HostLanguage", name = "anchor", substitutionHeadNamespace = "http://www.w3.org/2001/SMIL20/Language", substitutionHeadName = "anchor")
    public JAXBElement<AnchorType> createAnchor(AnchorType value) {
        return new JAXBElement<AnchorType>(_Anchor_QNAME, AnchorType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SeqType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/SMIL20/HostLanguage", name = "seq", substitutionHeadNamespace = "http://www.w3.org/2001/SMIL20/Language", substitutionHeadName = "seq")
    public JAXBElement<SeqType> createSeq(SeqType value) {
        return new JAXBElement<SeqType>(_Seq_QNAME, SeqType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MediaType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/SMIL20/HostLanguage", name = "audio", substitutionHeadNamespace = "http://www.w3.org/2001/SMIL20/Language", substitutionHeadName = "audio")
    public JAXBElement<MediaType> createAudio(MediaType value) {
        return new JAXBElement<MediaType>(_Audio_QNAME, MediaType.class, null, value);
    }

}
